<script lang="ts">
  /* global __FIRMWARE_VERSION__ */
  import { gt as semverGt } from "semver";

  import { modernEditorDevice, webMidiEnabled } from "$lib/stores";

  import { deviceForId } from "$lib/configuration";
  import { configuration } from "$lib/stores";

  const latestVersion = __FIRMWARE_VERSION__; // generated by vite.config.ts
  $: upgradeAvailable =
    $modernEditorDevice?.needsFirmwareUpdate ||
    ($configuration?.firmwareVersion &&
      latestVersion.trim() !== "" &&
      semverGt(latestVersion, $configuration.firmwareVersion));
  $: upgradeString = upgradeAvailable
    ? `A new version of the 8mu firmware (${latestVersion}) is available.`
    : "";
</script>

{#if $webMidiEnabled}
  <div class="details">
    <!-- <MidiSelector /> -->
    {#if $modernEditorDevice}
      <p class="device">
        Connected: <strong>{$modernEditorDevice.name}</strong>
        running firmware
        <strong>{$modernEditorDevice.firmwareVersion}</strong>
        {#if upgradeString}
          <span class="upgrade">
            {upgradeString}
            <a href="https://github.com/TomWhitwell/Smith-Kakehashi/releases"
              >Download</a
            >
          </span>
        {/if}
      </p>
    {:else if $configuration}
      <p class="device">
        Connected: <strong>{deviceForId($configuration.deviceId).name}</strong>
        running firmware
        <strong>{$configuration.firmwareVersion}</strong>
        {#if upgradeString}
          <span class="upgrade">
            {upgradeString}
            <a href="https://github.com/TomWhitwell/Smith-Kakehashi/releases"
              >Download</a
            >
          </span>
        {/if}
      </p>
    {:else}
      <p class="device">No device connected.</p>
    {/if}
  </div>
{/if}

<style>
  .details {
    flex: 1 0;
  }

  p.device {
    text-align: right;
  }
  span.upgrade {
    display: block;
    margin-top: 25px;
    border: 10px solid pink;
    border-image: repeating-linear-gradient(
        -55deg,
        #000,
        #000 5px,
        #ffb101 5px,
        #ffb101 10px
      )
      10;
    text-align: center;
    padding: 5px;
    background: #ffcc33;
  }
</style>
