<script lang="ts">
  /* global __FIRMWARE_VERSION__ */
  import { gt as semverGt } from "semver";

  import { webMidiEnabled } from "$lib/stores";

  import { deviceForId } from "$lib/configuration";
  import { configuration } from "$lib/stores";
  import { onDestroy } from "svelte";

  let upgradeString = "";
  let latestVersion = __FIRMWARE_VERSION__; // generated by vite.config.ts
  let versionCompared = false;

  const unsub = configuration.subscribe((c) => {
    if (
      c &&
      c.firmwareVersion &&
      latestVersion.trim() !== "" &&
      !versionCompared
    ) {
      versionCompared = true;
      if (semverGt(latestVersion, c.firmwareVersion)) {
        upgradeString = `A new version of the 16n firmware (${latestVersion}) is available.`;
      } else {
        upgradeString = "";
      }
    }
  });

  onDestroy(() => {
    unsub();
  });
</script>

{#if $webMidiEnabled}
  <div class="details">
    <!-- <MidiSelector /> -->
    {#if $configuration}
      <p class="device">
        Connected: <strong>{deviceForId($configuration.deviceId).name}</strong>
        running firmware
        <strong>{$configuration.firmwareVersion}</strong>
        {#if upgradeString.trim() != ""}
          <span class="upgrade">
            {upgradeString}
            <a href="https://github.com/16n-faderbank/16n/releases/latest"
              >Download</a
            >
          </span>
        {/if}
      </p>
    {:else}
      <p class="device">No device connected.</p>
    {/if}
  </div>
{/if}

<style>
  .details {
    flex: 1 0;
  }

  p.device {
    text-align: right;
  }
  span.upgrade {
    display: block;
    margin-top: 5px;
    color: #888;
  }
</style>
